<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTdspCv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTdspCv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQTdspCv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQTdspCv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQTdspCv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QTdspCv',
    'container.build_id' => 'd0d88a55',
    'container.build_time' => 1540880411,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTdspCv');
