<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGM5v5x\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGM5v5x/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXGM5v5x.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXGM5v5x\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXGM5v5x\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XGM5v5x',
    'container.build_id' => '350a4ab5',
    'container.build_time' => 1547028806,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGM5v5x');
