version: '3.1'

service:

    php:
       image: otezvikentiy/php7.2-fpm:0.0.11
       ports:
         - "9000:9000"
       volumes:
         - ./app:/var/www/app 
       working_dir: /app
       container_name: 'php-fpm'

    nginx:
      image: nginx:1.15.0
      ports:
        - "8080:80"
      volumes:
        - ./app:/var/www/app
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      container_name: 'nginx'

    postgres:
      image: postgres:9.6
      ports:
        - "5432:5432"
      working_dir: /app
      environment:
        POSTGRES_DB_FILE: test_db
        POSTGRES_USER_FILE: root
        POSTGRES_PASSWORD_FILE: ktkbn40k
      volumes:
        - ./data/dump:/app/dump
        - ./data/postgresql:/var/lib/postgresql/data
      container_name: 'postgresql'

    rabbitmq:
      image: rabbitmq:3.7.5-management
      working_dir: /app
      hostname: rabbit-mq
      ports:
        - '5672:5672'
        - '15672:15672'
      environment:
        RABBITMQ_DEFAULT_USER_FILE: user
        RABBITMQ_DEFAULT_PASS_FILE: password
        RABBITMQ_DEFAULT_VHOST_FILE: my_vhost
      container_name: 'rabbit-mq'
      
volumes:
  postgresql:
